apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <ommited>
    server: https://<SERVER_IP_ADDRESS>:6443 
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: oidc
  name: kubernetes
current-context: kubernetes
kind: Config
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://keycloak.example.com/realms/<realm>
      - --oidc-client-id=<YOUR_CLIENT_ID>
      - --oidc-auth-request-extra-params=acr_values=reauth
      - --oidc-pkce-method=S256
      command: kubectl
      env: null
      installHint: |
        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Chocolatey (Windows)
        choco install kubelogin
      interactiveMode: IfAvailable
      provideClusterInfo: false
